// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(rusty2600_mobileFFI)
import rusty2600_mobileFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_rusty2600_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_rusty2600_mobile_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A single running emulator instance.
 *
 * `#[uniffi::export]`ed methods take `&self` (`UniFFI` objects are always
 * handed to the host behind an `Arc`), so the mutable state lives behind a
 * `Mutex` — this crate is not performance-hot itself; the actual
 * frame-stepping cost is the same `System::step_instruction` loop every
 * other frontend already pays.
 */
public protocol MobileEmulatorProtocol : AnyObject {
    
    /**
     * Whether a ROM is currently loaded.
     */
    func isRomLoaded()  -> Bool
    
    /**
     * Load a ROM image, detecting its bankswitch scheme via
     * `rusty2600_cart::detect`. `rom_tag` is an opaque, host-supplied ROM
     * identity (e.g. a hash of `bytes`) used to validate save-states
     * against the currently-loaded ROM.
     *
     * # Errors
     *
     * Returns [`MobileError::UnrecognizedRom`] if `rusty2600_cart::detect`
     * doesn't recognize `bytes`' bankswitch scheme.
     */
    func loadRom(bytes: Data, romTag: UInt64) throws 
    
    /**
     * Restore a save-state blob captured for the currently-loaded ROM.
     *
     * # Errors
     *
     * Returns a [`MobileError::SaveState`] if `bytes` is malformed or was
     * captured for a different ROM (its embedded ROM tag doesn't match the
     * tag the currently-loaded ROM was given via `load_rom`).
     */
    func loadState(bytes: Data) throws 
    
    /**
     * Late-latch `input` into the RIOT/TIA ports (the same convention
     * every other frontend uses), then drive the system forward one frame
     * (until the VSYNC 1->0 edge), returning the cropped RGBA framebuffer
     * and this frame's drained/DC-blocked/normalized audio.
     *
     * # Errors
     *
     * Returns [`MobileError::NoRomLoaded`] if called before `load_rom`.
     */
    func runFrame(input: MobileInput) throws  -> FrameOutput
    
    /**
     * Capture the current system as a save-state blob (`[1.1.0]`
     * `SaveState`, tagged with the ROM tag `load_rom` was given).
     *
     * # Errors
     *
     * Returns [`MobileError::NoRomLoaded`] if called before `load_rom`.
     */
    func saveState() throws  -> Data
    
}

/**
 * A single running emulator instance.
 *
 * `#[uniffi::export]`ed methods take `&self` (`UniFFI` objects are always
 * handed to the host behind an `Arc`), so the mutable state lives behind a
 * `Mutex` — this crate is not performance-hot itself; the actual
 * frame-stepping cost is the same `System::step_instruction` loop every
 * other frontend already pays.
 */
open class MobileEmulator:
    MobileEmulatorProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_rusty2600_mobile_fn_clone_mobileemulator(self.pointer, $0) }
    }
    /**
     * Construct a fresh, unloaded emulator instance.
     */
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_rusty2600_mobile_fn_constructor_mobileemulator_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_rusty2600_mobile_fn_free_mobileemulator(pointer, $0) }
    }

    

    
    /**
     * Whether a ROM is currently loaded.
     */
open func isRomLoaded() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_rusty2600_mobile_fn_method_mobileemulator_is_rom_loaded(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Load a ROM image, detecting its bankswitch scheme via
     * `rusty2600_cart::detect`. `rom_tag` is an opaque, host-supplied ROM
     * identity (e.g. a hash of `bytes`) used to validate save-states
     * against the currently-loaded ROM.
     *
     * # Errors
     *
     * Returns [`MobileError::UnrecognizedRom`] if `rusty2600_cart::detect`
     * doesn't recognize `bytes`' bankswitch scheme.
     */
open func loadRom(bytes: Data, romTag: UInt64)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_rusty2600_mobile_fn_method_mobileemulator_load_rom(self.uniffiClonePointer(),
        FfiConverterData.lower(bytes),
        FfiConverterUInt64.lower(romTag),$0
    )
}
}
    
    /**
     * Restore a save-state blob captured for the currently-loaded ROM.
     *
     * # Errors
     *
     * Returns a [`MobileError::SaveState`] if `bytes` is malformed or was
     * captured for a different ROM (its embedded ROM tag doesn't match the
     * tag the currently-loaded ROM was given via `load_rom`).
     */
open func loadState(bytes: Data)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_rusty2600_mobile_fn_method_mobileemulator_load_state(self.uniffiClonePointer(),
        FfiConverterData.lower(bytes),$0
    )
}
}
    
    /**
     * Late-latch `input` into the RIOT/TIA ports (the same convention
     * every other frontend uses), then drive the system forward one frame
     * (until the VSYNC 1->0 edge), returning the cropped RGBA framebuffer
     * and this frame's drained/DC-blocked/normalized audio.
     *
     * # Errors
     *
     * Returns [`MobileError::NoRomLoaded`] if called before `load_rom`.
     */
open func runFrame(input: MobileInput)throws  -> FrameOutput {
    return try  FfiConverterTypeFrameOutput.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_rusty2600_mobile_fn_method_mobileemulator_run_frame(self.uniffiClonePointer(),
        FfiConverterTypeMobileInput.lower(input),$0
    )
})
}
    
    /**
     * Capture the current system as a save-state blob (`[1.1.0]`
     * `SaveState`, tagged with the ROM tag `load_rom` was given).
     *
     * # Errors
     *
     * Returns [`MobileError::NoRomLoaded`] if called before `load_rom`.
     */
open func saveState()throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_rusty2600_mobile_fn_method_mobileemulator_save_state(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileEmulator: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MobileEmulator

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MobileEmulator {
        return MobileEmulator(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MobileEmulator) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileEmulator {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MobileEmulator, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileEmulator_lift(_ pointer: UnsafeMutableRawPointer) throws -> MobileEmulator {
    return try FfiConverterTypeMobileEmulator.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileEmulator_lower(_ value: MobileEmulator) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMobileEmulator.lower(value)
}


/**
 * One frame's rendered output: an RGBA8 framebuffer (160x192, the same
 * `ATARI_W`/`ATARI_H` the wasm canvas-2D bootstrap uses).
 *
 * Also carries this frame's drained, DC-blocked, normalized audio samples
 * (`f32`, `[-1.0, 1.0]`) at the TIA's native ~31.4 kHz rate — the host is
 * responsible for resampling to its own audio output rate (Android's
 * `AudioTrack`/`AAudio`, iOS's `AVAudioEngine`, both support arbitrary
 * input sample rates).
 */
public struct FrameOutput {
    /**
     * RGBA8 framebuffer, `160 * 192 * 4` bytes.
     */
    public var rgba: Data
    /**
     * This frame's drained, DC-blocked, normalized audio samples.
     */
    public var audioSamples: [Float]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * RGBA8 framebuffer, `160 * 192 * 4` bytes.
         */rgba: Data, 
        /**
         * This frame's drained, DC-blocked, normalized audio samples.
         */audioSamples: [Float]) {
        self.rgba = rgba
        self.audioSamples = audioSamples
    }
}



extension FrameOutput: Equatable, Hashable {
    public static func ==(lhs: FrameOutput, rhs: FrameOutput) -> Bool {
        if lhs.rgba != rhs.rgba {
            return false
        }
        if lhs.audioSamples != rhs.audioSamples {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rgba)
        hasher.combine(audioSamples)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFrameOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FrameOutput {
        return
            try FrameOutput(
                rgba: FfiConverterData.read(from: &buf), 
                audioSamples: FfiConverterSequenceFloat.read(from: &buf)
        )
    }

    public static func write(_ value: FrameOutput, into buf: inout [UInt8]) {
        FfiConverterData.write(value.rgba, into: &buf)
        FfiConverterSequenceFloat.write(value.audioSamples, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrameOutput_lift(_ buf: RustBuffer) throws -> FrameOutput {
    return try FfiConverterTypeFrameOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrameOutput_lower(_ value: FrameOutput) -> RustBuffer {
    return FfiConverterTypeFrameOutput.lower(value)
}


/**
 * The complete host-input snapshot for one frame — the mobile-side
 * equivalent of `rusty2600_frontend::input::InputState`.
 *
 * `joystick0`/`joystick1` and `paddle0..=paddle3` (rather than
 * `[MobileJoystick; 2]`/`[MobilePaddle; 4]`) because `UniFFI`'s `Record`
 * derive doesn't support fixed-size array fields — only named fields or
 * `Vec<T>`. Named fields keep the generated Kotlin/Swift struct's shape
 * simple (no index-based access into a bridged array type).
 */
public struct MobileInput {
    /**
     * Port 0 joystick.
     */
    public var joystick0: MobileJoystick
    /**
     * Port 1 joystick.
     */
    public var joystick1: MobileJoystick
    /**
     * Paddle A.
     */
    public var paddle0: MobilePaddle
    /**
     * Paddle B.
     */
    public var paddle1: MobilePaddle
    /**
     * Paddle C.
     */
    public var paddle2: MobilePaddle
    /**
     * Paddle D.
     */
    public var paddle3: MobilePaddle
    /**
     * The console-switch panel.
     */
    public var switches: MobileSwitches

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Port 0 joystick.
         */joystick0: MobileJoystick, 
        /**
         * Port 1 joystick.
         */joystick1: MobileJoystick, 
        /**
         * Paddle A.
         */paddle0: MobilePaddle, 
        /**
         * Paddle B.
         */paddle1: MobilePaddle, 
        /**
         * Paddle C.
         */paddle2: MobilePaddle, 
        /**
         * Paddle D.
         */paddle3: MobilePaddle, 
        /**
         * The console-switch panel.
         */switches: MobileSwitches) {
        self.joystick0 = joystick0
        self.joystick1 = joystick1
        self.paddle0 = paddle0
        self.paddle1 = paddle1
        self.paddle2 = paddle2
        self.paddle3 = paddle3
        self.switches = switches
    }
}



extension MobileInput: Equatable, Hashable {
    public static func ==(lhs: MobileInput, rhs: MobileInput) -> Bool {
        if lhs.joystick0 != rhs.joystick0 {
            return false
        }
        if lhs.joystick1 != rhs.joystick1 {
            return false
        }
        if lhs.paddle0 != rhs.paddle0 {
            return false
        }
        if lhs.paddle1 != rhs.paddle1 {
            return false
        }
        if lhs.paddle2 != rhs.paddle2 {
            return false
        }
        if lhs.paddle3 != rhs.paddle3 {
            return false
        }
        if lhs.switches != rhs.switches {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(joystick0)
        hasher.combine(joystick1)
        hasher.combine(paddle0)
        hasher.combine(paddle1)
        hasher.combine(paddle2)
        hasher.combine(paddle3)
        hasher.combine(switches)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileInput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileInput {
        return
            try MobileInput(
                joystick0: FfiConverterTypeMobileJoystick.read(from: &buf), 
                joystick1: FfiConverterTypeMobileJoystick.read(from: &buf), 
                paddle0: FfiConverterTypeMobilePaddle.read(from: &buf), 
                paddle1: FfiConverterTypeMobilePaddle.read(from: &buf), 
                paddle2: FfiConverterTypeMobilePaddle.read(from: &buf), 
                paddle3: FfiConverterTypeMobilePaddle.read(from: &buf), 
                switches: FfiConverterTypeMobileSwitches.read(from: &buf)
        )
    }

    public static func write(_ value: MobileInput, into buf: inout [UInt8]) {
        FfiConverterTypeMobileJoystick.write(value.joystick0, into: &buf)
        FfiConverterTypeMobileJoystick.write(value.joystick1, into: &buf)
        FfiConverterTypeMobilePaddle.write(value.paddle0, into: &buf)
        FfiConverterTypeMobilePaddle.write(value.paddle1, into: &buf)
        FfiConverterTypeMobilePaddle.write(value.paddle2, into: &buf)
        FfiConverterTypeMobilePaddle.write(value.paddle3, into: &buf)
        FfiConverterTypeMobileSwitches.write(value.switches, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileInput_lift(_ buf: RustBuffer) throws -> MobileInput {
    return try FfiConverterTypeMobileInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileInput_lower(_ value: MobileInput) -> RustBuffer {
    return FfiConverterTypeMobileInput.lower(value)
}


/**
 * One joystick's four directions + fire, active-HIGH (`true` = pressed) —
 * a host-language-friendly convention, not a hardware register mirror.
 */
public struct MobileJoystick {
    /**
     * Up.
     */
    public var up: Bool
    /**
     * Down.
     */
    public var down: Bool
    /**
     * Left.
     */
    public var left: Bool
    /**
     * Right.
     */
    public var right: Bool
    /**
     * The single fire button.
     */
    public var fire: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Up.
         */up: Bool, 
        /**
         * Down.
         */down: Bool, 
        /**
         * Left.
         */left: Bool, 
        /**
         * Right.
         */right: Bool, 
        /**
         * The single fire button.
         */fire: Bool) {
        self.up = up
        self.down = down
        self.left = left
        self.right = right
        self.fire = fire
    }
}



extension MobileJoystick: Equatable, Hashable {
    public static func ==(lhs: MobileJoystick, rhs: MobileJoystick) -> Bool {
        if lhs.up != rhs.up {
            return false
        }
        if lhs.down != rhs.down {
            return false
        }
        if lhs.left != rhs.left {
            return false
        }
        if lhs.right != rhs.right {
            return false
        }
        if lhs.fire != rhs.fire {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(up)
        hasher.combine(down)
        hasher.combine(left)
        hasher.combine(right)
        hasher.combine(fire)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileJoystick: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileJoystick {
        return
            try MobileJoystick(
                up: FfiConverterBool.read(from: &buf), 
                down: FfiConverterBool.read(from: &buf), 
                left: FfiConverterBool.read(from: &buf), 
                right: FfiConverterBool.read(from: &buf), 
                fire: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MobileJoystick, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.up, into: &buf)
        FfiConverterBool.write(value.down, into: &buf)
        FfiConverterBool.write(value.left, into: &buf)
        FfiConverterBool.write(value.right, into: &buf)
        FfiConverterBool.write(value.fire, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileJoystick_lift(_ buf: RustBuffer) throws -> MobileJoystick {
    return try FfiConverterTypeMobileJoystick.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileJoystick_lower(_ value: MobileJoystick) -> RustBuffer {
    return FfiConverterTypeMobileJoystick.lower(value)
}


/**
 * One paddle's position (`0..=255`) + fire button.
 */
public struct MobilePaddle {
    /**
     * Pot position, `0` (fully clockwise) ..= `255` (fully counter-clockwise).
     */
    public var position: UInt8
    /**
     * The paddle's fire button.
     */
    public var fire: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Pot position, `0` (fully clockwise) ..= `255` (fully counter-clockwise).
         */position: UInt8, 
        /**
         * The paddle's fire button.
         */fire: Bool) {
        self.position = position
        self.fire = fire
    }
}



extension MobilePaddle: Equatable, Hashable {
    public static func ==(lhs: MobilePaddle, rhs: MobilePaddle) -> Bool {
        if lhs.position != rhs.position {
            return false
        }
        if lhs.fire != rhs.fire {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(position)
        hasher.combine(fire)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobilePaddle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobilePaddle {
        return
            try MobilePaddle(
                position: FfiConverterUInt8.read(from: &buf), 
                fire: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MobilePaddle, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.position, into: &buf)
        FfiConverterBool.write(value.fire, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobilePaddle_lift(_ buf: RustBuffer) throws -> MobilePaddle {
    return try FfiConverterTypeMobilePaddle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobilePaddle_lower(_ value: MobilePaddle) -> RustBuffer {
    return FfiConverterTypeMobilePaddle.lower(value)
}


/**
 * The six-switch console panel.
 */
public struct MobileSwitches {
    /**
     * Game Select (momentary).
     */
    public var select: Bool
    /**
     * Game Reset (momentary).
     */
    public var reset: Bool
    /**
     * `true` = Color, `false` = B&W.
     */
    public var color: Bool
    /**
     * `true` = A ("pro"), `false` = B ("amateur").
     */
    public var leftDifficulty: Bool
    /**
     * `true` = A ("pro"), `false` = B ("amateur").
     */
    public var rightDifficulty: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Game Select (momentary).
         */select: Bool, 
        /**
         * Game Reset (momentary).
         */reset: Bool, 
        /**
         * `true` = Color, `false` = B&W.
         */color: Bool, 
        /**
         * `true` = A ("pro"), `false` = B ("amateur").
         */leftDifficulty: Bool, 
        /**
         * `true` = A ("pro"), `false` = B ("amateur").
         */rightDifficulty: Bool) {
        self.select = select
        self.reset = reset
        self.color = color
        self.leftDifficulty = leftDifficulty
        self.rightDifficulty = rightDifficulty
    }
}



extension MobileSwitches: Equatable, Hashable {
    public static func ==(lhs: MobileSwitches, rhs: MobileSwitches) -> Bool {
        if lhs.select != rhs.select {
            return false
        }
        if lhs.reset != rhs.reset {
            return false
        }
        if lhs.color != rhs.color {
            return false
        }
        if lhs.leftDifficulty != rhs.leftDifficulty {
            return false
        }
        if lhs.rightDifficulty != rhs.rightDifficulty {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(select)
        hasher.combine(reset)
        hasher.combine(color)
        hasher.combine(leftDifficulty)
        hasher.combine(rightDifficulty)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileSwitches: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileSwitches {
        return
            try MobileSwitches(
                select: FfiConverterBool.read(from: &buf), 
                reset: FfiConverterBool.read(from: &buf), 
                color: FfiConverterBool.read(from: &buf), 
                leftDifficulty: FfiConverterBool.read(from: &buf), 
                rightDifficulty: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MobileSwitches, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.select, into: &buf)
        FfiConverterBool.write(value.reset, into: &buf)
        FfiConverterBool.write(value.color, into: &buf)
        FfiConverterBool.write(value.leftDifficulty, into: &buf)
        FfiConverterBool.write(value.rightDifficulty, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileSwitches_lift(_ buf: RustBuffer) throws -> MobileSwitches {
    return try FfiConverterTypeMobileSwitches.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileSwitches_lower(_ value: MobileSwitches) -> RustBuffer {
    return FfiConverterTypeMobileSwitches.lower(value)
}


/**
 * Everything that can go wrong loading a ROM or a save-state.
 */
public enum MobileError {

    
    
    /**
     * `rusty2600_cart::detect` didn't recognize the ROM image.
     */
    case UnrecognizedRom
    /**
     * A method that needs a running system was called before `load_rom`.
     */
    case NoRomLoaded
    /**
     * A `SaveState` operation failed (see the wrapped message).
     */
    case SaveState(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileError: FfiConverterRustBuffer {
    typealias SwiftType = MobileError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .UnrecognizedRom
        case 2: return .NoRomLoaded
        case 3: return .SaveState(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MobileError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .UnrecognizedRom:
            writeInt(&buf, Int32(1))
        
        
        case .NoRomLoaded:
            writeInt(&buf, Int32(2))
        
        
        case let .SaveState(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension MobileError: Equatable, Hashable {}

extension MobileError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_rusty2600_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_rusty2600_mobile_checksum_method_mobileemulator_is_rom_loaded() != 7459) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rusty2600_mobile_checksum_method_mobileemulator_load_rom() != 53537) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rusty2600_mobile_checksum_method_mobileemulator_load_state() != 28334) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rusty2600_mobile_checksum_method_mobileemulator_run_frame() != 55753) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rusty2600_mobile_checksum_method_mobileemulator_save_state() != 15505) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rusty2600_mobile_checksum_constructor_mobileemulator_new() != 64708) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all